// Code generated by tools/genk8sschema. DO NOT EDIT.
//
// Source: a pinned snapshot of the Kubernetes OpenAPI v2 ("swagger.json")
// document at internal/adapter/datasources/k8s/testdata/swagger.json.
// Regenerate with: make generate

package k8s

import _ "embed"

//go:embed schema_swagger_k8s_standard_resources.bin.gz
var swaggerSchemaDataGzip []byte
