package main

import (
	"bytes"
	"compress/gzip"
	"encoding/gob"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ebuildy/kubectl-sql/internal/port/schema"
)

// swaggerEntry is one resource's field tree. Entries are gob-encoded as a
// slice (not a map) so the embedded payload is byte-identical across runs:
// map iteration order is not deterministic, but a slice sorted by Key is.
type swaggerEntry struct {
	Key    string
	Fields []schema.Field
}

const goFileTemplate = `// Code generated by tools/genk8sschema. DO NOT EDIT.
//
// Source: a pinned snapshot of the Kubernetes OpenAPI v2 ("swagger.json")
// document at internal/adapter/datasources/k8s/testdata/swagger.json.
// Regenerate with: make generate

package k8s

import _ "embed"

//go:embed %s
var swaggerSchemaDataGzip []byte
`

// writeOutputs writes the gzip+gob binary asset and its sibling generated .go
// file (containing the //go:embed directive) next to outPath.
func writeOutputs(outPath string, entries []swaggerEntry) error {
	gz, err := encodeGzipGob(entries)
	if err != nil {
		return fmt.Errorf("encode: %w", err)
	}

	binPath := strings.TrimSuffix(outPath, ".go") + ".bin.gz"
	if err := os.WriteFile(binPath, gz, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", binPath, err)
	}

	content := fmt.Sprintf(goFileTemplate, filepath.Base(binPath))
	if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}

	return nil
}

func encodeGzipGob(entries []swaggerEntry) ([]byte, error) {
	var buf bytes.Buffer
	gw := gzip.NewWriter(&buf)
	if err := gob.NewEncoder(gw).Encode(entries); err != nil {
		return nil, fmt.Errorf("gob encode: %w", err)
	}
	if err := gw.Close(); err != nil {
		return nil, fmt.Errorf("gzip close: %w", err)
	}
	return buf.Bytes(), nil
}
